import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  geist,
  gtPlanar,
  gtPlanarItalic15,
  gtPlanarItalic30,
  gtPlanarItalic45,
  gtPlanarRetalic15,
  gtPlanarRetalic30,
  gtPlanarRetalic45,
  jetBrainsMono,
  tungsten,
} from "@/lib/fonts";
import "./globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx([
          tungsten.variable,
          jetBrainsMono.variable,
          gtPlanar.variable,
          geist.variable,
          gtPlanarItalic15.variable,
          gtPlanarItalic30.variable,
          gtPlanarItalic45.variable,
          gtPlanarRetalic15.variable,
          gtPlanarRetalic30.variable,
          gtPlanarRetalic45.variable,
        ])}
      >
        {children}
      </body>
    </html>
  );
}
